theme: jekyll-theme-slate
title: Welcome to IST707_GROUP_PROJECT_VIZ
description: This site is for hosting the IST07 interactive HTML visualizations for Samantha Brennen-Lisko, Holden Herrell, Jogesh Pugazhendhi, & Matthew Sutherland.
