theme: jekyll-theme-minimal
title: World Happiness Report Analytics
logo: /master/ischool-primary-vertical.png
description: By Samantha Brennen-Lisko, Holden Herrell, Jogesh Pugazhendhi, & Matthew Sutherland
