theme: jekyll-theme-minimal
title: World Happiness Report Analytics
logo: /gdc-world-happiness-report-2019.jpg
description: By Samantha Brennen-Lisko, Holden Herrell, Jogesh Pugazhendhi, & Matthew Sutherland
