theme: jekyll-theme-minimal
title: Word Happiness Report Analytics
logo: /ischool-primary-vertical.png
description: By Samantha Brennen-Lisko, Holden Herrell, Jogesh Pugazhendhi, & Matthew Sutherland
